# Mostly system specific, if you can handle more or less, change these for your needs
org.gradle.jvmargs=-Xmx3G
org.gradle.workers.max=5
org.gradle.parallel=true

# Mod Information
mod.version=2.5.2+edge
mod.name=Sounds
mod.id=sounds

# Dependencies
deps.fabric_loader=0.18.4
deps.mru=1.0.32+26.1.2
deps.yacl=3.9.3+26.1