# Mostly system specific, if you can handle more or less, change these for your needs
org.gradle.jvmargs=-Xmx3G
org.gradle.workers.max=5
org.gradle.parallel=true

# Mod Information
mod.version=2.5.0+lts
mod.name=Sounds
mod.id=sounds

# Dependencies
deps.fabric_loader=0.18.4
deps.yumi_mc_foundation=1.0.0+26.1