modLoader="javafml"
loaderVersion="${target_loader}"
issueTrackerURL="https://github.com/IMB11/Sounds/issues"
displayURL="http://IMB11.dev/"
logoFile="assets/sounds/icon.png"
authors="IMB11"
clientSideOnly = true
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description="${mod_description}"

[[dependencies.sounds]]
modId="${loader}"
type="required"
versionRange="${target_loader}"
ordering="NONE"
side="CLIENT"

[[dependencies.sounds]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange="[${target_yacl},)"
side="CLIENT"

[[dependencies.sounds]]
modId="minecraft"
type="required"
versionRange="${target_minecraft}"
ordering="NONE"
side="CLIENT"

[[dependencies.sounds]]
modId="mru"
type="required"
versionRange="[${target_mru},)"
ordering="NONE"
side="CLIENT"

[[dependencies.sounds]]
modId = "rsls"
type = "optional"
versionRange = ""
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config="sounds.mixins.json"